import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import type { ToolReport } from "@/types";

// Dot Matrix aesthetic carried into print (§9): black bg, white text, red key
// numbers. Silkscreen web font won't render in react-pdf, so the wordmark uses
// a bold built-in font + the signature red square.

const C = {
  bg: "#000000",
  surface: "#0A0A0A",
  border: "#1A1A1A",
  fg: "#FFFFFF",
  muted: "#888888",
  accent: "#FF0000",
};

const s = StyleSheet.create({
  page: { backgroundColor: C.bg, color: C.fg, padding: 36, fontFamily: "Courier" },
  headerRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 24 },
  brandRow: { flexDirection: "row", alignItems: "center" },
  square: { width: 10, height: 10, backgroundColor: C.accent, marginRight: 6 },
  wordmark: { fontFamily: "Courier-Bold", fontSize: 16, letterSpacing: 1 },
  metaRight: { textAlign: "right" },
  toolName: { fontSize: 11, color: C.fg },
  date: { fontSize: 9, color: C.muted, marginTop: 2 },
  headline: { backgroundColor: C.surface, borderColor: C.border, borderWidth: 1, padding: 16, marginBottom: 18 },
  headlineLabel: { fontSize: 9, color: C.muted, textTransform: "uppercase", marginBottom: 6 },
  headlineValue: { fontSize: 28, color: C.fg, fontFamily: "Courier-Bold" },
  section: { marginBottom: 14 },
  sectionHeading: { fontSize: 10, color: C.fg, textTransform: "uppercase", marginBottom: 6, fontFamily: "Courier-Bold" },
  row: { flexDirection: "row", justifyContent: "space-between", borderBottomColor: C.border, borderBottomWidth: 1, paddingVertical: 4 },
  rowLabel: { fontSize: 10, color: C.muted },
  rowValue: { fontSize: 10, color: C.fg },
  rowValueAccent: { fontSize: 10, color: C.accent, fontFamily: "Courier-Bold" },
  notes: { marginTop: 8 },
  note: { fontSize: 8, color: C.muted, marginBottom: 2 },
  footer: { position: "absolute", bottom: 24, left: 36, right: 36, borderTopColor: C.border, borderTopWidth: 1, paddingTop: 8 },
  footerText: { fontSize: 7, color: C.muted, textAlign: "center" },
});

function ReportBody({ report, date }: { report: ToolReport; date: string }) {
  return (
    <>
      <View style={s.headerRow}>
        <View style={s.brandRow}>
          <View style={s.square} />
          <Text style={s.wordmark}>CREATORSUITE</Text>
        </View>
        <View style={s.metaRight}>
          <Text style={s.toolName}>{report.toolName}</Text>
          <Text style={s.date}>{date}</Text>
        </View>
      </View>

      <View style={s.headline}>
        <Text style={s.headlineLabel}>{report.headline.label}</Text>
        <Text style={s.headlineValue}>{report.headline.value}</Text>
      </View>

      {report.sections.map((sec, i) => (
        <View key={i} style={s.section}>
          <Text style={s.sectionHeading}>{sec.heading}</Text>
          {sec.rows.map((r, j) => (
            <View key={j} style={s.row}>
              <Text style={s.rowLabel}>{r.label}</Text>
              <Text style={r.accent ? s.rowValueAccent : s.rowValue}>{r.value}</Text>
            </View>
          ))}
        </View>
      ))}

      {report.notes?.length ? (
        <View style={s.notes}>
          {report.notes.map((n, i) => (
            <Text key={i} style={s.note}>
              {n}
            </Text>
          ))}
        </View>
      ) : null}
    </>
  );
}

const FOOTER =
  "Generated by CreatorSuite · creatorsuite.vercel.app · Estimates only — not financial advice.";

/** Single-tool branded PDF (§9). */
export function ToolPdfDocument({ report }: { report: ToolReport }) {
  const date = new Date().toLocaleString("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  });
  return (
    <Document title={`CreatorSuite — ${report.toolName}`}>
      <Page size="A4" style={s.page}>
        <ReportBody report={report} date={date} />
        <View style={s.footer} fixed>
          <Text style={s.footerText}>{FOOTER}</Text>
        </View>
      </Page>
    </Document>
  );
}

/** Combined Rate Card PDF — one page per pinned estimate (§9). */
export function RateCardPdfDocument({ reports }: { reports: ToolReport[] }) {
  const date = new Date().toLocaleString("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  });
  return (
    <Document title="CreatorSuite — Rate Card">
      {reports.map((report, i) => (
        <Page key={i} size="A4" style={s.page}>
          <ReportBody report={report} date={date} />
          <View style={s.footer} fixed>
            <Text style={s.footerText}>{FOOTER}</Text>
          </View>
        </Page>
      ))}
    </Document>
  );
}
